export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const SIGNOUT_REQUEST = 'SIGNOUT_REQUEST'


export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const PRELOADER = 'PRELOADER';

//Posts action types
export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const DISAPPROVE_POST = 'DISAPPROVE_POST';
export const UNAPPROVED_POSTS = 'UNAPPROVED_POSTS';
export const APPROVE_POST = 'APPROVE_POST';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const GET_USER_POSTS = 'GET_USER_POSTS';
export const GET_USER_MEDIA = 'GET_USER_MEDIA';
export const CREATE_COMMENTS = 'CREATE_COMMENTS'
export const GET_POST_ID = 'GET_POST_ID';
export const GET_USER_POSTS_BY_ID = "GET_USER_POSTS_BY_ID";
export const GET_USER_ALL_IMAGES_BY_ID = "GET_USER_ALL_IMAGES_BY_ID"

//Events action types
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const CREATE_EVENT = 'CREATE_EVENT';
export const GET_EVENT_BY_ID = 'GET_EVENT_BY_ID';
export const REGISTER_FOR_EVENT = 'REGISTER_FOR_EVENT';
export const GET_EVENT_REGISTERED_USERS = 'GET_EVENT_REGISTERED_USERS';


//Profile action types
export const GET_CURRENT_PROFILE = "GET_CURRENT_PROFILE";
export const GET_CURRENT_PROFILE_ERROR = "GET_CURRENT_PROFILE_ERROR";
export const GET_PROFILE = "GET_PROFILE";
export const ADD_PROFILE = "ADD_PROFILE";
export const ADD_AVATAR = "ADD_AVATAR";
export const GET_ALL_PROFILES = "GET_ALL_PROFILES";
export const GET_ALL_PROFILES_ERROR = "GET_ALL_PROFILES_ERROR";
export const GET_USER_PROFILE_BY_ID = "GET_USER_PROFILE_BY_ID";
export const GET_USER_IMAGES = "GET_USER_IMAGES";


//CurrentPosts types
export const GET_CURRENT_POSTS = "CURRENT_POSTS";


//Ask Leader types
export const POST_ASK_LEADER = "POST_ASK_LEADER ";
export const GET_MY_QUE_IN_MY_UI = "GET_MY_QUE_IN_MY_UI";
export const POST_REPLY_TO_LEADER_ANS = "POST_REPLY_TO_LEADER_ANS";
export const GET_ALL_QUES_FOR_LEADER = "GET_ALL_QUES_FOR_LEADER";
export const POST_ASK_LEADER_REPLY = "POST_ASK_LEADER_REPLY";
export const MAKE_LEADER = "MAKE_LEADER";

// export const POST_ASK_USER_REPLY = "POST_ASK_USER_REPLY";


//community types 
export const CREATE_COMMUNITY_GROUP = " CREATE_COMMUNITY_GROUP"
export const GET_ALL_COMMUNITY_DETAILS = "GET_ALL_COMMUNITY_DETAILS"
export const GET_COMMUNITY_BY_ID = "GET_COMMUNITY_BY_ID"
export const LIKE_COMMUNITY_POST = "LIKE_COMMUNITY_POST"
export const ADD_COMMUNITY_COMMENTS = "ADD_COMMUNITY_COMMENTS"
export const GET_COMMUNITY_COMMENTS_BY_ID = "GET_COMMUNITY_COMMENTS_BY_ID"
export const ADD_COMMUNITY_AVATAR = "ADD_COMMUNITY_AVATAR"
export const ADD_COMMUNITY_COVERPIC = "ADD_COMMUNITY_COVERPIC"
export const UNLIKE_COMMUNITY_POST = "UNLIKE_COMMUNITY_POST";
export const SHARE_COMMUNITY_POST = "SHARE_COMMUNITY_POST";
export const ADD_COMMUNITY_MEMBERS = "ADD_COMMUNITY_MEMBERS";
export const ADD_GROUP_ADMIN = "ADD_GROUP_ADMIN";
export const EDIT_ABOUT_COMMUNITY = "EDIT_ABOUT_COMMUNITY";
export const GET_USER_COMMUNITIES = "GET_USER_COMMUNITIES";

//Giev types


export const GET_ALL_GIEV = "GET_ALL_GIEV"
export const GET_ALL_GIEV_SUCCESS = "GET_ALL_GIEV_SUCCESS"
export const GET_ALL_GIEV_FAILURE = "GET_ALL_GIEV_FAILURE"

export const FULLFILL_WISH_TO_CHILD = "FULLFILL_WISH_TO_CHILD"
export const GIEV_FORMS_UPLOAD = "GIEV_FORMS_UPLOAD"
export const GET_CHILD_DETAILS = "GET_CHILD_DETAILS"
export const EDIT_CHILD_DETAILS = "EDIT_CHILD_DETAILS"


//B'day nd Anniversary nd ServiceAnniversary
export const GET_FRIEND_BIRTHDAY = "GET_FRIEND_BIRTHDAY";
export const GET_ALL_FRIENDS_BIRTHDAY = "GET_ALL_FRIENDS_BIRTHDAY";
export const GET_FRIEND_SERVICE_ANNIVERSARY = "GET_FRIEND_SERVICE_ANNIVERSARY";
export const GET_ALL_FRIENDS_SERVICE_ANNIVERSARY = "GET_ALL_FRIENDS_SERVICE_ANNIVERSARY";
export const GET_FRIEND_WEDDING_ANNIVERSARY = "GET_FRIEND_WEDDING_ANNIVERSARY";
export const GET_ALL_FRIENDS_WEDDING_ANNIVERSARY = "GET_ALL_FRIENDS_WEDDING_ANNIVERSARY";
export const SEND_WISH_TEMPLATE = "SEND_WISH_TEMPLATE";
export const GET_BIRTHDAY_TEMPLATE = "GET_BIRTHDAY_TEMPLATE";
export const GET_SERVICE_ANNIVERSARY_TEMPLATE = "GET_SERVICE_ANNIVERSARY_TEMPLATE";
export const GET_WEDDING_ANNIVERSARY_TEMPLATE = "GET_WEDDING_ANNIVERSARY_TEMPLATE";
export const SEND_WISH_TO_MAIL = "SEND_WISH_TO_MAIL"

//Get up comming Birthday'S, Service'S nd Wedding'S Anniversery
export const GET_ALL_BIRTHDAYS_IN_UPCOMING_WEEK = "GET_ALL_BIRTHDAYS_IN_UPCOMING_WEEK";
export const GET_ALL_SERVICE_ANNIVERSARY_IN_UPCOMING_WEEK = "GET_ALL_SERVICE_ANNIVERSARY_IN_UPCOMING_WEEK"
export const GET_ALL_WEDDING_ANNIVERSARY_IN_UPCOMING_WEEK = "GET_ALL_WEDDING_ANNIVERSARY_IN_UPCOMING_WEEK"
export const BIRTHDAY_CAKE_REMINDER = "BIRTHDAY_CAKE_REMINDER"
export const WEDDING_CAKE_REMINDER = "WEDDING_CAKE_REMINDER"
export const SERVICE_CAKE_REMINDER = "SERVICE_CAKE_REMINDER"

//my connections
export const GET_CONNECTOINS = "GET_CONNECTOINS";
export const POST_CONNECT = "POST_CONNECT"
export const GET_CONNECTION_REQUESTS = "GET_CONNECTION_REQUESTS"
export const ACCEPT_CONNECTIONS = "ACCEPT_CONNECTIONS"
export const REJECT_CONNECTIONS = "REJECT_CONNECTIONS"

//GIEV Module
export const ADD_KIDS_WISHES = "ADD_KIDS_WISHES";

//Leaders
export const GET_ALL_LEADER = "GET_ALL_LEADER";
export const GET_KID_WISHES = "GET_KID_WISHES";
export const ADD_TO_CART = "ADD_TO_CART";
export const GET_CART_ITEM = "GET_CART_ITEM";


//Badges
export const UPLOAD_ADGES_BY_ADMIN = "UPLOAD_ADGES_BY_ADMIN";
export const GET_ALL_FRESH_BADGES = "GET_ALL_FRESH_BADGES";
export const SEND_BADGE_TO_USER = "SEND_BADGE_TO_USER";
export const RECIVE_BADGE_FROM_USER = "RECIVE_BADGE_FROM_USER";

//Get Post
export const GET_POST_START = 'GET_POST_START';
export const GET_POST_FAILURE = 'GET_POST_FAILURE';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';

// ADD Post
export const ADD_POST_START = 'ADD_POST_START';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

//ADD GIEVS TO CART

export const ADD_WISHES_TO_CART_START = 'ADD_WISHES_TO_CART_START';
export const ADD_WISHES_TO_CART_SUCCESS = 'ADD_WISHES_TO_CART_SUCCESS'
export const ADD_WISHES_TO_CART_FAILURE = 'ADD_WISHES_TO_CART_FAILURE';


export const GET_CARTITEM_START = 'GET_CARTITEM_START';
export const GET_CARTITEM_SUCCESS = 'GET_CARTITEM_SUCCESS'
export const GET_CARTITEM_FAILURE = 'GET_CARTITEM_FAILURE';

export const DELETE_POST_START = 'DELETE_POST_START'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'